# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'Farzad Abdolhosseini'
description: 'Persoanl Webpage'
permalink: pretty
logo: "https://picsum.photos/1/1?image=1" #"https://avatars0.githubusercontent.com/u/5062458?s=460&v=4"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  # About: /about/
  # Blog: /blog/
  Projects: /projects/

# Footer nav
navigation_footer:
  # Back to top: "#top"
  Github:
    icon: github-circle
    url: "https://github.com/farzadab/"
  Stack Overflow:
    icon: stack-overflow
    url: "https://stackoverflow.com/users/6793148/farzad-abdolhosseini"
  LinkedIn:
    icon: linkedin-box
    url: "https://www.linkedin.com/in/farzadab/"
  UBC Webpage:
    icon: school
    url: "https://www.cs.ubc.ca/~farzadab/page/"


# FavIcons
favicons:
  16: "/assets/img/logo/logo-16.png"
  32: "/assets/img/logo/logo-32.png"
  64: "/assets/img/logo/logo-64.png"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
  project_pages:
    title: Projects
    output: true
    description: "My Projects"
    feature_text: ""
    # feature_image: "https://picsum.photos/2560/600?image=923&blur=1"
    # feature_image: "https://picsum.photos/2560/600?image=538"
    feature_image: "/assets/img/seagull2.jpg"
